name: Tweet release
on:
  release:
    types: [published]
    
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - id: meta
        name: Get release version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: ethomson/send-tweet-action@v1
        with:
          status: "Release of viSens-S version ${% raw %}{{ steps.meta.output.VERSION }}{% endraw %} is available! Download it here https://github.com/Albert-Alvarez/viSens-S/releases/latest #visens #masb #electrochemical #software"          
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}    
